In [72]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [73]:
main_data = pd.read_csv('../data/main_dataset.csv')

In [74]:
main_features = main_data.loc[:,'population':].drop(['restaurant_count','N'], axis=1)

In [75]:
population = main_features['population']
population

0      21242.0
1      43752.0
2      11506.0
3       9287.0
4       9287.0
        ...
301    23383.0
302    12295.0
303    25029.0
304     6677.0
305    11230.0
Name: population, Length: 306, dtype: float64

In [76]:
yelp_types = pd.read_csv('../data/data/yelp_restaurant_type_counts_1km.csv').drop('Unnamed: 0', axis=1)
yelp_types

,caribbean,cocktailbars,seafood,spanish,chinese,breakfast_brunch,japanese,thai,wraps,juicebars,...,pharmacy,farmersmarket,foodtours,bowling,syrian,southafrican,eventservices,bookstores,homedecor,diyfood
0,17.0,1.0,3.0,1.0,4.0,3.0,1.0,1.0,1.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,5.0,0.0,4.0,0.0,4.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7.0,0.0,5.0,0.0,1.0,4.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,2.0,1.0,2.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,2.0,2.0,0.0,3.0,1.0,3.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,0.0,9.0,4.0,3.0,2.0,7.0,2.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302,2.0,2.0,2.0,1.0,4.0,2.0,0.0,1.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
303,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
304,0.0,4.0,3.0,1.0,6.0,6.0,2.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
305,1.0,0.0,2.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [64]:
google_types = pd.read_csv('../data/data/google_counts_v3.csv', index_col=0)
google_types

,index,lodging,restaurant,school,health,bar,church,bank,store,clothing,tourist attraction,department store,office,electronics store,park,supermarket
0,nyu_2451_34572.0,9,55,26,13,10,60,12,36,19,0,2,7,11,5,15
1,nyu_2451_34572.1,5,39,26,7,4,25,15,37,34,0,3,7,6,8,11
2,nyu_2451_34572.2,3,33,16,3,11,23,4,36,13,1,2,4,3,3,8
3,nyu_2451_34572.3,2,54,27,7,14,5,24,19,4,4,0,1,1,19,4
4,nyu_2451_34572.4,3,20,25,9,16,12,23,19,5,2,0,6,2,19,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,nyu_2451_34572.301,39,60,60,20,60,37,60,60,60,12,9,57,29,20,26
302,nyu_2451_34572.302,3,44,6,9,8,20,3,33,6,1,2,5,1,8,8
303,nyu_2451_34572.303,4,32,15,6,2,18,7,34,12,2,0,5,9,9,12
304,nyu_2451_34572.304,19,59,36,10,19,25,12,36,7,4,0,11,9,19,8
305,nyu_2451_34572.305,2,36,14,7,8,30,10,50,14,2,1,8,2,11,17

In [65]:
all_features = pd.concat([population, google_types, yelp_types], axis=1)

In [66]:
all_features.to_csv('../data/data/all_features_counts_v3.csv')

In [89]:
main_features = all_features.drop('index', axis=1)

In [90]:
# divide all rows by population
for row in range(main_features.shape[0]):
   main_features.iloc[row] = main_features.iloc[row].div(main_features.iloc[row]['population'])

In [91]:
main_features

,population,lodging,restaurant,school,health,bar,church,bank,store,clothing,...,pharmacy,farmersmarket,foodtours,bowling,syrian,southafrican,eventservices,bookstores,homedecor,diyfood
0,1.0,0.000424,0.002589,0.001224,0.000612,0.000471,0.002825,0.000565,0.001695,0.000894,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.000114,0.000891,0.000594,0.000160,0.000091,0.000571,0.000343,0.000846,0.000777,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.000261,0.002868,0.001391,0.000261,0.000956,0.001999,0.000348,0.003129,0.001130,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.000215,0.005815,0.002907,0.000754,0.001507,0.000538,0.002584,0.002046,0.000431,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.000323,0.002154,0.002692,0.000969,0.001723,0.001292,0.002477,0.002046,0.000538,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,1.0,0.001668,0.002566,0.002566,0.000855,0.002566,0.001582,0.002566,0.002566,0.002566,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302,1.0,0.000244,0.003579,0.000488,0.000732,0.000651,0.001627,0.000244,0.002684,0.000488,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
303,1.0,0.000160,0.001279,0.000599,0.000240,0.000080,0.000719,0.000280,0.001358,0.000479,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
304,1.0,0.002846,0.008836,0.005392,0.001498,0.002846,0.003744,0.001797,0.005392,0.001048,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
305,1.0,0.000178,0.003206,0.001247,0.000623,0.000712,0.002671,0.000890,0.004452,0.001247,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [92]:
# remove population
main_features = main_features.drop('population', axis=1)

In [93]:
main_features

,lodging,restaurant,school,health,bar,church,bank,store,clothing,tourist attraction,...,pharmacy,farmersmarket,foodtours,bowling,syrian,southafrican,eventservices,bookstores,homedecor,diyfood
0,0.000424,0.002589,0.001224,0.000612,0.000471,0.002825,0.000565,0.001695,0.000894,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000114,0.000891,0.000594,0.000160,0.000091,0.000571,0.000343,0.000846,0.000777,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000261,0.002868,0.001391,0.000261,0.000956,0.001999,0.000348,0.003129,0.001130,0.000087,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000215,0.005815,0.002907,0.000754,0.001507,0.000538,0.002584,0.002046,0.000431,0.000431,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000323,0.002154,0.002692,0.000969,0.001723,0.001292,0.002477,0.002046,0.000538,0.000215,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,0.001668,0.002566,0.002566,0.000855,0.002566,0.001582,0.002566,0.002566,0.002566,0.000513,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302,0.000244,0.003579,0.000488,0.000732,0.000651,0.001627,0.000244,0.002684,0.000488,0.000081,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
303,0.000160,0.001279,0.000599,0.000240,0.000080,0.000719,0.000280,0.001358,0.000479,0.000080,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
304,0.002846,0.008836,0.005392,0.001498,0.002846,0.003744,0.001797,0.005392,0.001048,0.000599,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
305,0.000178,0.003206,0.001247,0.000623,0.000712,0.002671,0.000890,0.004452,0.001247,0.000178,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [94]:
# scaling
scaler = StandardScaler()
main_features_scaled = pd.DataFrame(scaler.fit_transform(main_features), columns=main_features.columns)
main_features_scaled

,lodging,restaurant,school,health,bar,church,bank,store,clothing,tourist attraction,...,pharmacy,farmersmarket,foodtours,bowling,syrian,southafrican,eventservices,bookstores,homedecor,diyfood
0,-0.079968,-0.146167,-0.161173,-0.156556,-0.188736,-0.013981,-0.260805,-0.174098,-0.171366,-0.170146,...,-0.05726,-0.05726,-0.078602,-0.090721,-0.069491,-0.05726,-0.05726,-0.070138,-0.070138,-0.05726
1,-0.192748,-0.219922,-0.207891,-0.298483,-0.245454,-0.190940,-0.300563,-0.215886,-0.183289,-0.170146,...,-0.05726,-0.05726,-0.078602,-0.090721,-0.069491,-0.05726,-0.05726,-0.070138,-0.070138,-0.05726
2,-0.139366,-0.134053,-0.148814,-0.266851,-0.116182,-0.078824,-0.299703,-0.103521,-0.147447,-0.135238,...,-0.05726,-0.05726,-0.078602,-0.090721,-0.069491,-0.05726,-0.05726,-0.070138,-0.070138,-0.05726
3,-0.155906,-0.006054,-0.036291,-0.112049,-0.033730,-0.193533,0.100711,-0.156818,-0.218487,0.002849,...,-0.05726,-0.05726,-0.078602,-0.090721,-0.069491,-0.05726,-0.05726,-0.070138,-0.070138,-0.05726
4,-0.116657,-0.165092,-0.052268,-0.044428,-0.001530,-0.134336,0.081434,-0.156818,-0.207546,-0.083649,...,-0.05726,-0.05726,-0.078602,-0.090721,-0.069491,-0.05726,-0.05726,-0.070138,-0.070138,-0.05726
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,0.373544,-0.147176,-0.061613,-0.080153,0.124531,-0.111543,0.097436,-0.131221,-0.001521,0.035978,...,-0.05726,-0.05726,-0.078602,-0.090721,-0.069491,-0.05726,-0.05726,-0.070138,-0.070138,-0.05726
302,-0.145464,-0.103183,-0.215774,-0.118874,-0.161837,-0.108062,-0.318258,-0.125411,-0.212666,-0.137478,...,-0.05726,-0.05726,-0.078602,-0.090721,-0.069491,-0.05726,-0.05726,-0.070138,-0.070138,-0.05726
303,-0.176151,-0.203104,-0.207517,-0.273449,-0.247176,-0.179335,-0.311871,-0.190651,-0.213535,-0.138051,...,-0.05726,-0.05726,-0.078602,-0.090721,-0.069491,-0.05726,-0.05726,-0.070138,-0.070138,-0.05726
304,0.802824,0.125213,0.148020,0.121544,0.166339,0.058242,-0.040191,0.007846,-0.155725,0.070471,...,-0.05726,-0.05726,-0.078602,-0.090721,-0.069491,-0.05726,-0.05726,-0.070138,-0.070138,-0.05726
305,-0.169488,-0.119386,-0.159491,-0.152997,-0.152611,-0.026011,-0.202522,-0.038381,-0.135577,-0.098614,...,-0.05726,-0.05726,-0.078602,-0.090721,-0.069491,-0.05726,-0.05726,-0.070138,-0.070138,-0.05726

In [95]:
# export
main_features_scaled.to_csv('../data/data/all_features_scaled.csv', index=False)